//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketPOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSale
    {
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public string Name { get; set; }
        public System.DateTime EventDate { get; set; }
        public string OrderGuid { get; set; }
        public bool IsFulfilled { get; set; }
        public bool IsToGo { get; set; }
        public bool IsWalkUp { get; set; }
        public bool IsValid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Notes { get; set; }
        public string PaymentType { get; set; }
    }
}
